version: 2
updates:
    - package-ecosystem: composer
      directory: "/"
      schedule:
          interval: daily
      labels:
          - "dependencies"
          - "automerge"
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
      labels:
          - "dependencies"
          - "automerge"
