version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Datagrid!234"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Datagrid!234" -C -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
